### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by sayri23** [NodeMiraiPlugins/NodeMiraiFGOGacha#6]
![IMG_20210509_093334](https://user-images.githubusercontent.com/62638560/117557822-ab9bad00-b0a9-11eb-83a1-31c6d6ed94b9.jpg)
请问如何解决

**Comment by sayri23** [comment]
安装依赖后解决了上面的问题，但是再第一次运行时自动更新了资源后就退出了，再运行也没反应

**Comment by RedBeanN** [comment]
> 安装依赖后解决了上面的问题，但是再第一次运行时自动更新了资源后就退出了，再运行也没反应

直接退出应该是 [node-mirai-sdk](https://github.com/RedBeanN/node-mirai) 没有配置好

**Comment by sayri23** [comment]
> > 安装依赖后解决了上面的问题，但是再第一次运行时自动更新了资源后就退出了，再运行也没反应
> 
> 直接退出应该是 [node-mirai-sdk](https://github.com/RedBeanN/node-mirai) 没有配置好

额
请问这个应该如何配置，需要打开哪些模块？

**Comment by sayri23** [comment]
![IMG_20210523_204917](https://user-images.githubusercontent.com/62638560/119261096-5c588f00-bc08-11eb-958f-ee9763287838.jpg)
每次都是这样😂下载完就直接退出了，不知道怎么搞

**Comment by RedBeanN** [comment]
> ![IMG_20210523_204917](https://user-images.githubusercontent.com/62638560/119261096-5c588f00-bc08-11eb-958f-ee9763287838.jpg)
> 每次都是这样😂下载完就直接退出了，不知道怎么搞

``` javascript
// node-mirai-sdk 的配置
const bot = new Mirai(...);
bot.on('authed', () => {
  bot.verify();
});
bot.listen('all');

// FGOGacha 的配置
bot.use(FGOGacha(...));
```

**Comment by sayri23** [comment]
这是在index.js里的代码？好像没找到。。。

**Comment by sayri23** [comment]
可以写个详细点的教程吗😂

**Comment by sayri23** [comment]
请问这个怎么解决，是
/home/lighthouse/fgogacha/index.js:208



SyntaxError: Unexpected end of input
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by RedBeanN** [comment]
> 请问这个怎么解决，是
> /home/lighthouse/fgogacha/index.js:208
> 
> SyntaxError: Unexpected end of input
> at wrapSafe (internal/modules/cjs/loader.js:979:16)
> at Module._compile (internal/modules/cjs/loader.js:1027:27)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> at Module.load (internal/modules/cjs/loader.js:928:32)
> at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
> at internal/main/run_main_module.js:17:47

看你自己的`index.js`第208行

**Comment by sayri23** [comment]
![MB{54~38V_JFDKR$V%I~NLX](https://user-images.githubusercontent.com/62638560/128459736-bd521894-d85b-456a-8f64-d263c8a10e26.png)

**Comment by sayri23** [comment]
> > 请问这个怎么解决，是
> > /home/lighthouse/fgogacha/index.js:208
> > SyntaxError: Unexpected end of input
> > at wrapSafe (internal/modules/cjs/loader.js:979:16)
> > at Module._compile (internal/modules/cjs/loader.js:1027:27)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> > at Module.load (internal/modules/cjs/loader.js:928:32)
> > at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> > at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
> > at internal/main/run_main_module.js:17:47
> 
> 看你自己的`index.js`第208行

跑起来了但是只要superadmin可以设置卡池，群员们不行

**Comment by sayri23** [comment]
[init] Ready to init
[NodeMirai] Installed plugin [ NodeMiraiFgoGacha ]
Failed @ auth: Invalid host
[init] Downloaded bg-mc-icon.png
[init] Downloading https://fgo.wiki/w/%E6%8A%BD%E5%8D%A1%E6%A8%A1%E6%8B%9F%E5%99%A8 for pools.json
[init] Saved pools.json
[init] Downloading pools for gacha.json and icons.json
(node:2592525) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at getGachaPools (/home/lighthouse/bot/NodeMiraiFGOGacha-master/src/getGachaPools.js:41:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async init (/home/lighthouse/bot/NodeMiraiFGOGacha-master/init.js:47:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2592525) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2592525) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
请问下载资源时出错如何解决

**Comment by RedBeanN** [comment]
> [init] Ready to init
> [NodeMirai] Installed plugin [ NodeMiraiFgoGacha ]
> Failed @ auth: Invalid host
> [init] Downloaded bg-mc-icon.png
> [init] Downloading https://fgo.wiki/w/%E6%8A%BD%E5%8D%A1%E6%A8%A1%E6%8B%9F%E5%99%A8 for pools.json
> [init] Saved pools.json
> [init] Downloading pools for gacha.json and icons.json
> (node:2592525) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
> at getGachaPools (/home/lighthouse/bot/NodeMiraiFGOGacha-master/src/getGachaPools.js:41:65)
> at processTicksAndRejections (internal/process/task_queues.js:95:5)
> at async init (/home/lighthouse/bot/NodeMiraiFGOGacha-master/init.js:47:3)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:2592525) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:2592525) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 请问下载资源时出错如何解决

更新插件即可
```sh
npm i -S node-mirai-fgo-gacha@latest
```
